services:
  okblog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: okblog-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - okblog-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 10s
      retries: 5

  okblog-kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: okblog-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://okblog-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      okblog-elasticsearch:
        condition: service_healthy
    networks:
      - okblog-network

networks:
  okblog-network:
    external: true

volumes:
  elasticsearch_data: 