services:
  search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okblog-search-service
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200
      - ELASTICSEARCH_INDEX=profile-service-logs
    ports:
      - "3003:3001"
    restart: unless-stopped