services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: okblog-search-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:9201"]
      interval: 30s
      timeout: 10s
      retries: 5

  search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okblog-search-service
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9201
      - ELASTICSEARCH_INDEX=posts
    ports:
      - "3003:3001"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  esdata:
    driver: local 