services:
  search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okblog-search-service
    environment:
      - ELASTICSEARCH_URL=http://host.docker.internal:9200
      - ELASTICSEARCH_INDEX=post-db.okblog.posts
    ports:
      - "3003:3001"