services:
  postgres:
    image: postgres:14
    container_name: profile-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: profile
      DB_SSLMODE: disable
      PORT: 8080
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY:-my_secret_key}
      USE_KIBANA_LOGGING: "true"
      ELASTICSEARCH_URL: "http://host.docker.internal:9200"
      ELASTICSEARCH_INDEX: "profile-service-logs"
      SERVICE_NAME: "profile-service"
      ONLY_ONE_PROFILE: "true"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: profile-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - default

volumes:
  postgres_data:

networks:
  default: