services:
  app:
    build: .
    container_name: post-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://post-db:3306/okblog?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      # Kibana logging configuration
      - KIBANA_LOGGING_ENABLED=true
      - ELASTICSEARCH_URL=http://host.docker.internal:9200
      - ELASTICSEARCH_INDEX=post-service-logs
      - SERVICE_NAME=post-service
    depends_on:
      - db
    networks:
      - okblog-network

  db:
    image: mysql:8.1
    container_name: post-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=okblog
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - okblog-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: post-phpmyadmin
    environment:
      - PMA_HOST=post-db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - okblog-network

networks:
  okblog-network:
    driver: bridge

volumes:
  mysql_data: 