services:
  okblog-post:
    build: .
    container_name: okblog-post
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://okblog-mysql:3306/okblog?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      # Kibana logging configuration
      - KIBANA_LOGGING_ENABLED=true
      - ELASTICSEARCH_URL=http://okblog-elasticsearch:9200
      - ELASTICSEARCH_INDEX=okblog-post-logs
      - SERVICE_NAME=okblog-post
      - NEW_RELIC_LICENSE_KEY=ABCD1234567890
      - NEW_RELIC_APP_NAME=okblog-post
    depends_on:
      - okblog-mysql
    networks:
      - okblog-network

  okblog-mysql:
    image: mysql:8.1
    container_name: okblog-mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=okblog
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin=mysql-bin --binlog-format=ROW
    networks:
      - okblog-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=okblog-mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "8082:80"
    depends_on:
      - okblog-mysql
    networks:
      - okblog-network

  okblog-zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    container_name: okblog-zookeeper
    ports:
      - "2181:2181"
    networks:
      - okblog-network

  okblog-kafka:
    image: debezium/kafka:2.7.3.Final
    container_name: okblog-kafka
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_CONNECT=okblog-zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://okblog-kafka:9092
    depends_on:
      - okblog-zookeeper
    networks:
      - okblog-network

  okblog-debezium:
    image: debezium/connect:2.7.3.Final
    container_name: okblog-debezium
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=okblog-kafka:9092
      - GROUP_ID=debezium-connect
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - okblog-kafka
      - okblog-mysql
    networks:
      - okblog-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8086:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=okblog-kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=okblog-zookeeper:2181
    depends_on:
      - okblog-kafka
      - okblog-zookeeper
    networks:
      - okblog-network

networks:
  okblog-network:
    external: true

volumes:
  mysql_data: 