services:
  okblog-nginx:
    image: nginx:stable-alpine
    container_name: okblog-nginx
    ports:
      - "80:80"
    volumes:
      - ./api-gateway.conf:/etc/nginx/nginx.conf:ro
      - ./cors-preflight.conf:/etc/nginx/cors-preflight.conf:ro
      - ./common-headers.conf:/etc/nginx/common-headers.conf:ro
      - ./cache:/data/nginx/cache
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s