services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okblog-admin
    ports:
      - "3001:80"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - ADMIN_API_BASE_URL=http://localhost:80/api
      - UPLOADED_FILE_HOST=http://localhost:4566/