services:
  okblog-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okblog-admin
    ports:
      - "3006:80"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - ADMIN_API_BASE_URL=http://localhost:80/api
      - UPLOADED_FILE_HOST=http://localhost:4566/
    networks:
      - okblog-network

networks:
  okblog-network:
    external: true