services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okblog-admin
    ports:
      - "3001:80"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - ADMIN_API_BASE_URL=http://host.docker.internal:80/api
    restart: unless-stopped 