name: Deploy Admin Service

env:
    CONTEXT_DIR: './'
    CAPROVER_APP: okblog-admin

on:
  push:
    tags:
      - 'admin-*-*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: |
            echo "FULL_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/okblog:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            echo "ADDITIONAL_BUILD_ARGS=--build-arg VITE_ADMIN_API_BASE_URL=${{ vars.ADMIN_API_BASE_URL }} --build-arg VITE_UPLOADED_FILE_HOST=${{ vars.ADMIN_UPLOADED_FILE_HOST }}" >> $GITHUB_ENV

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push Release 
          shell: bash
          run: |
            cd ./admin
            cp ../build_and_push.sh ./
            ./build_and_push.sh
          
        - name: Deploy App to CapRover
          uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
          with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            app: '${{ env.CAPROVER_APP }}'
            token: '${{ secrets.CAPROVER_ADMIN_APP_TOKEN }}'
            image: '${{ env.FULL_IMAGE_NAME }}' 