name: Deploy Post Service

on:
  push:
    tags:
      - 'post-*-*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/post-}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./post
          file: ./post/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/okblog:${{ env.VERSION }}

      - name: Deploy to CapRover
        uses: caprover/deploy-action@v1
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          token: ${{ secrets.CAPROVER_POST_APP_TOKEN }}
          appName: okblog-post
          imageName: ${{ secrets.DOCKERHUB_USERNAME }}/okblog:${{ env.VERSION }} 