name: Deploy Profile Service

env:
    CONTEXT_DIR: './'
    CAPROVER_APP: okblog-profile

on:
  push:
    tags:
      - 'profile-*-*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: |
            echo "FULL_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/okblog:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.24'
        
        - name: Install dependencies
          run: |
            cd ./tag
            go mod tidy
        
        - name: Run tests
          run: |
            cd ./tag
            go build -v ./... 
            go test -v ./... 

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push Release 
          shell: bash
          run: |
            cp ./build_and_push.sh ./profile/
            cd ./profile
            ./build_and_push.sh

        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: '${{ env.FULL_IMAGE_NAME }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
          
        - name: Deploy App to CapRover
          uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
          with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            app: '${{ env.CAPROVER_APP }}'
            token: '${{ secrets.CAPROVER_PROFILE_APP_TOKEN }}'
            image: '${{ env.FULL_IMAGE_NAME }}'