name: Deploy Profile Service

env:
    CONTEXT_DIR: './'
    IMAGE_NAME: ${{ github.repository }}/profile
    DOCKERFILE: ./profile/Dockerfile
    CAPROVER_APP: okblog-profile
    DOCKER_REGISTRY: ghcr.io

on:
  push:
    tags:
      - 'profile-*-*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: |
            echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
            export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
            echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA-gitsha" >> $GITHUB_ENV

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version: 1.24

        - name: Build and test
          run: |
            cd ./profile
            go mod tidy
            go build -v ./...

        - name: Log in to the Container registry
          uses: docker/login-action@v2
          with:
              registry: ${{ env.DOCKER_REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and Push Release to Docker Registry
          shell: bash
          run: ./build_and_push.sh ${{ env.DOCKERFILE }}
          
        - name: Deploy App to CapRover
          uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
          with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            app: '${{ env.CAPROVER_APP }}'
            token: '${{ secrets.CAPROVER_PROFILE_APP_TOKEN }}'
            image: '${{ env.FULL_IMAGE_NAME }}'