name: Deploy Search Service

env:
    CONTEXT_DIR: './'
    CAPROVER_APP: okblog-search

on:
  push:
    tags:
      - 'search-*-*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: |
            echo "FULL_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/okblog:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Install Rust toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true

        - name: Cache Rust dependencies
          uses: actions/cache@v4
          with:
            path: |
              ~/.cargo/registry
              ~/.cargo/git
              search/target
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            restore-keys: ${{ runner.os }}-cargo-

        - name: Build search service
          working-directory: ./search
          run: cargo build --release

        - name: Run tests
          working-directory: ./search
          run: cargo test

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push Release 
          shell: bash
          run: |
            cp ./build_and_push.sh ./search/
            cd ./search
            ./build_and_push.sh
          
        - name: Deploy App to CapRover
          uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
          with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            app: '${{ env.CAPROVER_APP }}'
            token: '${{ secrets.CAPROVER_SEARCH_APP_TOKEN }}'
            image: '${{ env.FULL_IMAGE_NAME }}' 
