name: Deploy Web Service

env:
    CONTEXT_DIR: './'
    CAPROVER_APP: okblog-web

on:
  push:
    tags:
      - 'web-*-*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - run: |
            echo "FULL_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/okblog:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push Release 
          shell: bash
          run: |
            cd ./web

            echo "NODE_ENV=production" > .env
            echo "BLOG_TITLE=${{ vars.WEB_BLOG_TITLE }}" >> .env
            echo "BLOG_DESCRIPTION=${{ vars.WEB_BLOG_DESCRIPTION }}" >> .env
            echo "API_URL=${{ vars.WEB_API_URL }}" >> .env
            echo "BROWSER_BASE_URL=${{ vars.WEB_BROWSER_BASE_URL }}" >> .env
            echo "UMAMI_SCRIPT_URL=${{ vars.WEB_UMAMI_SCRIPT_URL }}" >> .env
            echo "UMAMI_WEBSITE_ID=${{ vars.WEB_UMAMI_WEBSITE_ID }}" >> .env

            cp ../build_and_push.sh ./
            ./build_and_push.sh
          
        - name: Deploy App to CapRover
          uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
          with:
            server: '${{ secrets.CAPROVER_SERVER }}'
            app: '${{ env.CAPROVER_APP }}'
            token: '${{ secrets.CAPROVER_WEB_APP_TOKEN }}'
            image: '${{ env.FULL_IMAGE_NAME }}' 