services:
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: okblog-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - API_URL=http://localhost:80
      - BLOG_TITLE=OKBlog - Development
      - BLOG_DESCRIPTION=A modern blog for sharing your thoughts and ideas with the world
      - NITRO_LOG_LEVEL=info
      - DEBUG=nuxt:*
    # Configure logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Keep container running and restart on failure
    restart: unless-stopped
    # Enable TTY for better log output
    tty: true
    stdin_open: true