services:
  web-production:
    build:
      context: .
      dockerfile: Dockerfile
    image: okblog-web
    container_name: okblog-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - API_URL=http://localhost:80
      - BLOG_TITLE=OKBlog - Production
      - BLOG_DESCRIPTION=A modern blog built with Nuxt.js microservices
    
  # Development configuration with hot-reload
  web:
    image: node:20-alpine
    container_name: okblog-web-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - API_URL=http://localhost:80
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - BLOG_TITLE=OKBlog - Development
      - BLOG_DESCRIPTION=A modern blog for sharing your thoughts and ideas with the world
    command: sh -c "npm install && npm run dev"